Fix shared metrics between requests
prometheus/mysqld_exporter pull request #722
Opened 2023-04-10 11:19 UTC by LeoQuote

## Breaking changes

### dropped metrics
* mysql_exporter_scrapes_total 
* mysql_exporter_scrape_errors_total
* mysql_last_scrape_failed 

### new metrics
* mysql_exporter_collector_success (replace mysql_exporter_scrape_errors_total)

### metrics isolated between requests
* mysql_up
* mysql_exporter_collector_success
* mysql_exporter_collector_duration_seconds

## Why is this neccessary
We are using mysqld_exporter in `multi-target` method, which means one exporter for multiple mysql instance, the crucial metric `mysql_up` must be isolated between requests, or there will be misunderstandings, some mysql instance would shown as down while in fact it is not.

all shared metrics are dropped especially `mysql_exporter_scrapes_total`  and `mysql_exporter_scrape_errors_total` , the metrics are useless since prometheus can record almost everything, including scrape fail for each collector.

`mysql_last_scrape_failed`  is covered by `mysql_exporter_collector_success` so it is also dropped.

fix #713

2023-04-10 12:00 UTC, SuperQ requested changes
Thanks, most of this makes sense. I think we should move all the Prometheus metric descriptors to package level vars to reduce the Go GC churn.

2023-04-10 12:13 UTC, LeoQuote commented on collector/exporter.go
> -	scrapeDurationDesc = prometheus.NewDesc(
Thanks for your review, I think it is the price that has to be paid using multiple  target scrape.

I’ll look into it either way.

2023-04-10 12:28 UTC, SuperQ commented on collector/exporter.go
> -	scrapeDurationDesc = prometheus.NewDesc(
Desc objects do not create metrics. They are just the identification of the metric itself. That doesn't happen until you do `MustNewConstMetric()`.

2023-04-10 12:29 UTC, SuperQ commented on collector/exporter.go
> +	ch <- e.up
For example here, if there was a `mysqlUpDesc` package var, you could do this:

```suggestion
	ch <- mysqlUpDesc
```

2023-04-11 04:38 UTC, SuperQ commented on collector/exporter.go
> +		ch <- prometheus.MustNewConstMetric(mysqlScrapeFailed, prometheus.GaugeValue, 0.0)
I wonder if we should just get rid of `mysql_last_scrape_failed`. It's basically the same thing as `mysql_up`.

2023-04-11 07:49 UTC, SuperQ approved these changes
Thanks!

2023-04-11 15:35 UTC, merged