Allow comment characters within configuration values when using my.cnf
prometheus/mysqld_exporter pull request #769
Opened 2023-09-12 15:26 UTC by buzztaiki

This PR will fix https://github.com/prometheus/mysqld_exporter/issues/376

I've configured `SpaceBeforeInlineComment` option to allow comment characters within values.
see https://github.com/go-ini/ini/blob/b2f570e5b5b844226bbefe6fb521d891f529a951/ini.go#L97-L101

2023-09-12 16:21 UTC, SuperQ commented
What about passwords with `#` or `;` in them?

2023-09-12 16:23 UTC, SuperQ commented
Oh, I see, this is to allow this. Wouldn't quotes used be a safer way to handle this?

2023-09-13 21:35 UTC, SuperQ requested changes
What prevents quotes around the value from solving this problem?

2023-09-18 19:47 UTC, patrickeasters commented
I stumbled upon this PR because I hit the same issue. Even when quoted, comment characters are still interpreted as the beginning of comments.

Here's a quick playspace demonstrating that using the same `ini` package: https://goplay.space/#dAkouM7WJ1T

2023-09-18 21:03 UTC, SuperQ commented
@patrickeasters Thanks for digging into the quoting. Perhaps we should update the README docs to recommend backtick quoting of passwords.

2023-09-18 21:34 UTC, SuperQ commented
I would also be fine with simply flipping `IgnoreInlineComment: true`.

2023-09-19 02:05 UTC, patrickeasters commented
Either of those sound better than the rabbit hole of reading docs of mysqld_exporter's dependencies and cursing the inconsistency of INI parsers. 😄 

Updating the README is of course the safest, but I don't imagine a ton of folks using inline comments in these INI files either.

2023-09-19 05:40 UTC, SuperQ commented
This needs a DCO sign-off. You can use `git commit -s --amend` to add it.

2026-09-06 19:24 UTC, ArthurSens commented
Hey, it looks like #937 already solved the same problem this one is trying to solve, so I'll close this one. Thank you anyway!

2026-09-06 19:24 UTC, closed without merging