support MySQL 8.4
prometheus/mysqld_exporter pull request #837
Opened 2024-05-15 05:42 UTC by mtanda

#### Summary

In MySQL 8.4, several "Replication SQL syntax" commands have been deprecated, requiring the use of new syntax. During testing, it was confirmed that errors occur with the old syntax. This PR updates the code to be compatible with the new syntax. Could you please review this PR?

#### Details

The changes address the syntax errors that arise due to the deprecated commands. Below are the specific errors encountered:

```
mysqld-exporter  | ts=2024-05-15T02:39:40.760Z caller=exporter.go:173 level=error msg="Error from scraper" scraper=slave_status target=mysql_replica:3306 err="Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SLAVE STATUS' at line 1"
mysqld-exporter  | ts=2024-05-15T02:43:26.471Z caller=exporter.go:173 level=error msg="Error from scraper" scraper=slave_hosts target=mysql_replica:3306 err="Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SLAVE HOSTS' at line 1"
```

For reference, you can find the MySQL 8.4 release notes here: [MySQL 8.4 Release Notes](https://dev.mysql.com/doc/refman/8.4/en/mysql-nutshell.html#mysql-nutshell-removals).

Thank you for reviewing this PR!

2024-05-15 07:04 UTC, SuperQ requested changes

2024-05-15 07:04 UTC, SuperQ commented on collector/slave_hosts.go
> +	for _, query := range slaveHostsQueries {
I'm not sure I like this for loop/break pattern. I would prefer to do a simple linear `if` drop through.

2024-05-15 07:04 UTC, SuperQ commented on collector/slave_hosts.go
> +	slaveHostsQueries = [2]string{"SHOW SLAVE HOSTS", "SHOW REPLICAS"}
I would rather keep the const and add a new `showReplicasQuery` const for the new version.

2024-05-15 07:53 UTC, mtanda commented
@SuperQ Thank you for the review! I have addressed the comments and made the necessary changes. Could you please review it again?

2024-05-15 07:58 UTC, SuperQ approved these changes
Thanks!

2024-05-15 07:58 UTC, SuperQ commented
I suppose we should add MySQL 8.4 to our CI pipeline.

2024-05-15 08:11 UTC, merged

2024-05-15 08:20 UTC, mtanda commented
Thanks for merge!!

2024-10-10 02:45 UTC, happywzy commented
Which version of docker solves this problem?