Set lock_wait_timeout option only if positive
prometheus/mysqld_exporter pull request #896
Opened 2024-11-21 19:11 UTC by festeveira

This PR conditionally sets the connection option lock_wait_timeout only if it is positive. This allows the user to define a negative value for this option via command line options and making the exporter work again with older versions of mysql, while still behaving the same way by default.

Was really helpful for me, I need to monitor several instances in multi target mode and most of them are unsupported versions. Unless you see a problem with this I think it would be nice to have it merged.

2025-02-19 12:23 UTC, SuperQ commented
I'm not generally a fan of "magic values" like this. I prefer more explicit settings.

2025-02-20 14:31 UTC, festeveira commented
Hello, thank you for your feedback! I have added a command line parameter to explicitly disable the option. What do you think?

2025-02-20 17:33 UTC, SuperQ requested changes

2025-02-20 17:33 UTC, SuperQ commented on README.md
> +exporter.disable_lock_wait_timeout         | Disable the lock_wait_timeout connection parameter. Makes the exporter compatible with older versions of MySQL. (default: false)
I prefer "positive" flags, so that we don't have double negative behavior.

The disable would be `--no-exporter.enable_lock_wait_timeout`.

```suggestion
exporter.enable_lock_wait_timeout         | Disable the lock_wait_timeout connection parameter. Makes the exporter compatible with older versions of MySQL. (default: true)
```

2025-02-20 17:34 UTC, SuperQ commented
Yes, as a boolean flag is better. Thanks.

2025-05-21 13:13 UTC, SuperQ approved these changes
Thanks!

2025-05-21 13:13 UTC, merged